version: "3.7"
services:
  postgres:
    container_name: postgres-typescript-api
    image: postgres:12.2
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-typescript-api
    image: dpage/pgadmin4:4.18
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  api:
    command: "npm run start:dev"
    ports:
      - "3030:3000"
      - "9229:9229"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: