version: "3.7"

services:
  api:
    container_name: typescript-api
    image: node:13.12.0-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules/